# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo DefaultWorkingDirectory $(System.DefaultWorkingDirectory)
- script: echo ArtifactsDirectory $(System.ArtifactsDirectory)
- script:  echo Pipeline.Workspace $(Pipeline.Workspace)
- script:  echo Pipeline.Workspace $(Build.ArtifactStagingDirectory)
